const $=s=>document.querySelector(s);const camera=$('#camera'),canvas=$('#visionCanvas'),ctx=canvas.getContext('2d');const startBtn=$('#startBtn'),status=$('#visionStatus'),hint=$('#hint'),toast=$('#toast'),cursor=$('#spatialCursor'),gestureState=$('#gestureState');let stream=null,vision=false,raf=0,handLandmarker=null,lastVideoTime=-1,pinched=false,dragTarget=null,dragOffsetX=0,dragOffsetY=0;
const MODEL_URL='https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task';
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();function notify(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}function clock(){$('#clock').textContent=new Intl.DateTimeFormat([], {hour:'2-digit',minute:'2-digit'}).format(new Date())}setInterval(clock,1000);clock();
async function loadHands(){try{const {HandLandmarker,FilesetResolver}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/+esm');const fileset=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm');handLandmarker=await HandLandmarker.createFromOptions(fileset,{baseOptions:{modelAssetPath:MODEL_URL,delegate:'GPU'},runningMode:'VIDEO',numHands:1,minHandDetectionConfidence:.55,minHandPresenceConfidence:.55,minTrackingConfidence:.55});status.textContent='HAND TRACKING READY';hint.textContent='Show one hand to the camera';notify('Hand tracking ready');return true}catch(e){console.warn('Hand tracking unavailable',e);status.textContent='CAMERA ACTIVE';hint.textContent='Hand model unavailable · pointer fallback active';return false}}
async function startVision(){if(vision)return;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30}},audio:false});camera.srcObject=stream;await camera.play();vision=true;document.body.classList.add('vision-on');status.textContent='STARTING HAND TRACKING';hint.textContent='Show one hand to the camera';startBtn.textContent='VISION ACTIVE';cursor.style.opacity='1';notify('Vision system online');loadHands();draw()}catch(e){status.textContent='CAMERA BLOCKED';hint.textContent='Allow camera access, then try again.';notify('Camera permission required')}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function processHand(result){if(!result?.landmarks?.length){gestureState.textContent='NO HAND';return}const lm=result.landmarks[0],index=lm[8],thumb=lm[4],wrist=lm[0],scale=dist(wrist,lm[9]);moveCursor((1-index.x)*innerWidth,index.y*innerHeight);setPinch(dist(index,thumb)<Math.max(.045,scale*.55))}
function moveCursor(x,y){x=Math.max(15,Math.min(innerWidth-15,x));y=Math.max(15,Math.min(innerHeight-15,y));cursor.style.left=`${x}px`;cursor.style.top=`${y}px`;const target=document.elementFromPoint(x,y)?.closest('.spatial-window:not(.closed)');document.querySelectorAll('.spatial-window').forEach(w=>w.classList.toggle('hovered',w===target));gestureState.textContent=target?(pinched?'GRAB':'TARGET'):'TRACKING';if(dragTarget){dragTarget.style.setProperty('--x',`${x-dragOffsetX}px`);dragTarget.style.setProperty('--y',`${y-dragOffsetY}px`)}}
function setPinch(value){if(value===pinched)return;pinched=value;cursor.classList.toggle('pinch',pinched);const x=parseFloat(cursor.style.left)||innerWidth/2,y=parseFloat(cursor.style.top)||innerHeight/2;if(pinched){const target=document.elementFromPoint(x,y)?.closest('.spatial-window:not(.closed)');if(target){dragTarget=target;const r=target.getBoundingClientRect();dragOffsetX=x-r.left;dragOffsetY=y-r.top;target.classList.add('selected');notify(`${target.dataset.window.toUpperCase()} grabbed`)}}else if(dragTarget){dragTarget.classList.remove('selected');dragTarget=null;notify('Released')}}
function draw(){if(!vision)return;ctx.clearRect(0,0,innerWidth,innerHeight);if(handLandmarker&&camera.readyState>=2&&camera.currentTime!==lastVideoTime){lastVideoTime=camera.currentTime;try{processHand(handLandmarker.detectForVideo(camera,performance.now()))}catch(e){console.warn(e)}}const t=performance.now()/1000,r=70+Math.sin(t*2)*5;ctx.beginPath();ctx.arc(innerWidth/2,innerHeight/2,r,0,Math.PI*2);ctx.strokeStyle='rgba(255,255,255,.10)';ctx.stroke();raf=requestAnimationFrame(draw)}
addEventListener('pointermove',e=>{if(vision&&!handLandmarker)moveCursor(e.clientX,e.clientY)});addEventListener('pointerdown',()=>{if(vision&&!handLandmarker)setPinch(true)});addEventListener('pointerup',()=>{if(vision&&!handLandmarker)setPinch(false)});startBtn.addEventListener('click',startVision);$('.dock').addEventListener('click',e=>{const b=e.target.closest('.dock-item');if(!b)return;document.querySelectorAll('.dock-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');notify(`${b.dataset.app.toUpperCase()} selected`)});document.querySelectorAll('.close-window').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();b.closest('.spatial-window').classList.add('closed');notify('Window closed')}));addEventListener('beforeunload',()=>{cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop())});
